test with lts16
I am getting weird stack errors with lts16 and earlier:
```
Hawk
error: Won't compile:
	<interactive>:1:1: error:
    attempting to use module ‘main:M1338261393241126579867105’ (/var/home/petersen/tmp/hint-c07f4e051b9e8d8f/M1338261393241126579867105.hs) which is not loaded
error: Won't compile:
	<interactive>:1:1: error:
    attempting to use module ‘main:M2120538248708628250867105’ (/var/home/petersen/tmp/hint-da65bcb72c3b99cd/M2120538248708628250867105.hs) which is not loaded
```